AWSTemplateFormatVersion: '2010-09-09'
Description: Destination S3 Bucket for deployment

Resources:
  DestinationBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: PublicRead
Outputs:
  DestinationBucketARN:
    Value: !GetAtt DestinationBucket.Arn
    Export:
      Name: DestinationArn