AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy Index.html from Source S3 Bucket to Destination S3 Bucket using AWS CodePipeline

Resources:
  SourceBucket:
    Type: 'AWS::S3::Bucket'

  DestinationBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: PublicRead  # Adjust based on your requirements
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html

  CodePipelineRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: CodePipelinePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 's3:GetObject'
                  - 's3:PutObject'
                Resource:
                  - !GetAtt SourceBucket.Arn
                  - !GetAtt DestinationBucket.Arn

  CodePipeline:
    Type: 'AWS::CodePipeline::Pipeline'
    Properties:
      ArtifactStore:
        Location: !Ref SourceBucket
        Type: S3
      Name: StaticWebsiteDeploymentPipeline
      RoleArn: !GetAtt CodePipelineRole.Arn
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: AWS
                Version: "1"
                Provider: S3
              Configuration:
                S3Bucket: !Ref SourceBucket
                S3ObjectKey: index.html
              OutputArtifacts:
                - Name: SourceArtifact

        - Name: Deploy
          Actions:
            - Name: DeployAction
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: "1"
                Provider: S3
              InputArtifacts:
                - Name: SourceArtifact
              Configuration:
                BucketName: !Ref DestinationBucket
                Extract: 'index.html'
              RunOrder: 1
