AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  Username:
    Description: username for github
    Default: "jayshreea0402"
    Type: String
  Repo:
    Description: repo name
    Default: testing-s3
    Type: String

Resources:
  SourceBucket44:
    Type: 'AWS::S3::Bucket'
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
    #   AccessControl: Private

  DestinationBucket44:
    Type: 'AWS::S3::Bucket'
    Properties:
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      #AccessControl: PublicRead 
      OwnershipControls:
        Rules:
        - ObjectOwnership: BucketOwnerPreferred
      
    # Properties:
    #   AccessControl: PublicRead
    #   WebsiteConfiguration:
    #     IndexDocument: index.html
    #     ErrorDocument: error.html
    #   OwnershipControls:
    #     Rules:
    #     - ObjectOwnership: BucketOwnerPreferred         

  PipelineRole44:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "Codepipelinerole44444"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "codepipeline.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: /
      Policies:
        - PolicyName: "code-pipeline-access"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "*"
                Resource: "*"
  
  FormationRole44:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "cloudFormationRole44444"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "cloudformation.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: /
      Policies:
        - PolicyName: CloudFormation-Role
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "*"
                Resource: "*"

  CodePipeline44:
    Type: 'AWS::CodePipeline::Pipeline'
    Properties:
      ArtifactStore:
        Location: !Ref SourceBucket44
        Type: S3
      Name: StaticWebsite
      RoleArn: !GetAtt PipelineRole44.Arn
      Stages:
        - Name: Source
          Actions:
            - Name: GithubRepo
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: "1"
                Provider: GitHub
              Configuration:
                Owner: !Ref Username
                Repo: testing-s3
                PollForSourceChanges: "false"
                Branch: main
                OAuthToken : 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
                #Token" : "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"
              OutputArtifacts:
                - Name: Sourcezip
              RunOrder: 1
         
        # Actions: 
        #     - Name: GithubRepo
        #       ActionTypeId: 
        #         Category: Source 
        #         Owner: ThirdParty
        #         Version: 1 
        #         Provider: GitHub 
        #       Configuration:
        #         "Owner": !Ref Username,
        #         "Repo": !Ref Password,
        #         "PollForSourceChanges": "false"
        #         "Branch": "main"
        #       OutputArtifacts:
        #         - Name: FrontendSourceOutput 
        #           RunOrder: 1
        #           S3Bucket: !Ref ArtifactStoreS3Bucket              #try
        #           S3ObjectKey: "source.zip"

        - Name: Deploy
          Actions:
            - Name: DeployAction
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: "1"
                Provider: S3
              InputArtifacts:
                - Name: Sourcezip
              Configuration:
                BucketName: !Ref DestinationBucket44
                Extract: true #'index.html'
              RunOrder: 1


